<section id="criar-conta">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <a href="#back" class="volta">
                    <i class="material-icons">arrow_back</i>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div>
                    <h3 class="titulo">Termos de Uso</h3>
                </div>
                <div class="texto mb-4 mt-2 float-left text-justify">
                    MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, pessoa jurídica de direito privado, inscrita no CNPJ/MF sob o nº xxx, é uma empresa que presta serviços de anúncios de serviços gerais via internet, através do aplicativo “MÃOCHEIA”, disponível para os sistemas Android e iOS, com o objetivo única e exclusivamente de aproximar e facilitar a comunicação entre dois segmentos de usuários da plataforma, denominados para efeito do presente Termo, “USUÁRIO CLIENTE” e “USUÁRIO PRESTADOR DE SERVIÇOS”.
                    <br><br>O presente Termo regula as condições de uso da plataforma MÃOCHEIA pelo USUÁRIO CLIENTE e pelo USUÁRIO PRESTADOR DE SERVIÇOS, sendo que estes, ao concordarem com os Termos aqui apresentados, se submetem a todas as condições de uso da plataforma.
                    <br><br>Ao utilizar o MÃOCHEIA, o USUÁRIO CLIENTE declara estar ciente de que os USUÁRIOS PRESTADORES DE SERVIÇOS não possuem qualquer vínculo empregatício com a empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, logo, prestam seus serviços de forma independente e autônoma, assumindo totalmente suas responsabilidades pelos serviços ofertados, utilizando seus próprios recursos, tais como, ferramentas, veículos, materiais, insumos, entre outros.
                    <br><br>Assim, a assinatura do presente instrumento não vincula o USUÁRIO CLIENTE e o USUÁRIO PRESTADOR DE SERVIÇOS à empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, sendo esta apenas encarregada da manutenção da plataforma, logo, cada parte é a titular única e exclusiva de suas responsabilidades trabalhistas, fiscais, tributárias, cíveis, criminais e comerciais, de acordo com a legislação brasileira, nos termos e condições que seguem:
                    <br><br><b>I – DO OBJETO</b>
                    <br><br>O objeto do presente contrato consiste em:
                    <br><br>I.1 Estabelecer as condições gerais de uso da plataforma MÃOCHEIA, às quais o USUÁRIO CLIENTE e o USUÁRIO PRESTADOR DE SERVIÇOS estarão submetidos ao assinarem este Termo, portanto, declarando-se cientes e concordes em relação ao seu conteúdo.
                    <br><br>I.2 Descrever as funcionalidades da plataforma, para que o USUÁRIO CLIENTE e o USUÁRIO PRESTADOR DE SERVIÇOS atestem sua adequação, ou não, às suas necessidades, e assim possam, sem qualquer intervenção da empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, decidir sobre sua utilização para negociação dos serviços de seu interesse.
                    <br><br><b>II – DAS CARACTERÍSTICAS E FUNCIONALIDADES DA PLATAFORMA</b>
                    <br><br>II.1 A plataforma MÃOCHEIA foi projetada para apresentar o maior número possível de prestadores de serviços dentro das mais diversas áreas de atuação, a uma também imensa gama de clientes interessados na contratação dos profissionais para a execução dos referidos serviços. Isso permitirá que o usuário que necessite consumir um determinado serviço “USUÁRIO CLIENTE”, encontre outro usuário “USUÁRIO PRESTADOR DE SERVIÇOS”, o qual possa atender às suas necessidades.
                    <br><br>II.2 Ao conectar o USUÁRIO PRESTADOR DE SERVIÇOS ao USUÁRIO CLIENTE, o MÃOCHEIA disponibiliza um espaço onde ambos podem adicionar dados pessoais e profissionais, além de informações sobre as características do serviço e orçamento, a seu critério e sob sua responsabilidade, a fim de que, livremente, portanto sem interferência da plataforma, negociem os preços e as condições em que se dará a prestação do serviço.
                    <br><br>II.3 A empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA  oferece unicamente serviços de manutenção do aplicativo MÃOCHEIA, não sendo fornecedora de quaisquer serviços anunciados através da plataforma, bem como não se envolve e nem interfere na contratação, execução, pagamento/recebimento, qualidade do atendimento, e tudo mais que envolva a negociação da prestação dos serviços, sendo de inteira responsabilidade dos USUÁRIOS.
                    <br><br>II.4 Assim, a MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, por não figurar como parte nas transações que se realizam entre o USUÁRIO CLIENTE e o USUÁRIO PRESTADOR DE SERVIÇOS, não pode obrigar os USUÁRIOS a honrarem as obrigações assumidas, cabendo aos mesmos a busca por meios legais para a sua viabilização.
                    <br><br>II.5 Como forma de manter registros referentes às prestações de serviços, o MÃOCHEIA disponibiliza ferramentas em sua plataforma, as quais os USUÁRIOS podem utilizar para enviar mensagens, imagens, debater preços, prazos, materiais, calendário, entre outros itens que compõem a relação comercial estabelecida, o que pode ser uma forma de proteger ambas as partes numa eventual controvérsia sobre a negociação havida.
                    <br><br>II.6 O MÃOCHEIA permite avaliações, tanto pelo USUÁRIO CLIENTE quanto pelo USUÁRIO PRESTADOR DE SERVIÇOS, a respeito da relação comercial estabelecida, sendo que estas avaliações serão publicadas nos seus perfis e ficarão disponíveis para consulta por outros USUÁRIOS que venham a utilizar a plataforma.
                    <br><br>II.7 Fica sob inteira responsabilidade dos USUÁRIOS o teor das avaliações feitas no MÃOCHEIA, porém a empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA se reserva o direito de excluir quaisquer avaliações que entender ofensivas, discriminatórias, difamatórias, ou ainda com qualquer outro sentido que não seja o de, estritamente, pontuar a conduta do USUÁRIO em relação ao serviço contratado.
                    <br><br><b>III – DO CADASTRO</b>
                    <br><br>III.1 Somente estão aptos a cadastrar-se na plataforma MÃOCHEIA, as pessoas físicas absolutamente capazes e pessoas jurídicas devidamente inscritas no Cadastro Nacional de Pessoas Jurídicas - CNPJ.
                    <br><br>III.2 Ao cadastrar-se, os USUÁRIOS poderão utilizar todos os serviços disponíveis na plataforma, bem como estarão consentindo com as condições de uso presentes neste Termo, inclusive declarando-se expressamente cientes de que o MÃOCHEIA fará a coleta e tratamento dos seus dados para seu pleno funcionamento.
                    <br><br>III.3 É de exclusiva responsabilidade dos USUÁRIOS fornecer, atualizar e garantir a veracidade dos dados cadastrais, não recaindo à MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, qualquer tipo de responsabilidade civil e/ou criminal resultante de dados inverídicos, incorretos ou incompletos fornecidos pelos mesmos.
                    <br><br>III.4 Não será permitido ao USUÁRIO utilizar apelidos que guardem semelhança com o nome MÃOCHEIA, bem como a plataforma poderá excluir, sem consentimento ou aviso prévio, cadastros que utilizem apelidos que insinuem ou sugiram que os serviços anunciados na plataforma são prestados pela MÃOCHEIA ANÚNCIOS DE INTERNET LTDA.
                    <br><br>III.5 O USUÁRIO acessará a sua conta na plataforma por meio de login e senha, comprometendo-se a não informar a terceiros estes dados, responsabilizando-se integralmente pelo uso dos mesmos, bem como por todas operações efetuadas em sua conta.
                    <br><br>III.6 A empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA  poderá, unilateralmente, sem prévio aviso ou anuência do USUÁRIO, bloquear ou suspender o uso de uma conta ou até mesmo excluir um cadastro previamente aceito, caso verificar a existência de qualquer forma de publicidade ou citação de serviços que possam ser ofensivos ou prejudiciais a outros USUÁRIOS, à plataforma ou a terceiros, caso em que não será obrigada a qualquer tipo de compensação por lucros cessantes ou indenização por danos morais.
                    <br><br>III.7 O MÃOCHEIA recusará a habilitação de cadastros de USUÁRIOS que tenham sido bloqueados ou excluídos por cometimento de infrações às políticas de utilização da plataforma ou à legislação vigente.
                    <br><br><b>IV – DO TRATAMENTO DE DADOS E DA POLÍTICA DE PRIVACIDADE</b>
                    <br><br>IV.1 O tratamento de dados pessoais e profissionais, bem como avaliações referentes à relação comercial estabelecida entre os USUÁRIOS através da utilização do MÃOCHEIA, são requisitos primordiais para o bom funcionamento da plataforma, uma vez que permitem que haja transparência quanto às atividades contratadas.
                    <br><br>IV.2 Ao assinar o presente Termo, o usuário autoriza expressamente o tratamento dos seus dados pessoais e profissionais pelo MÃOCHEIA, incluindo coleta, classificação, armazenamento, processamento, transmissão, estudos, e tudo mais que seja necessário para atingir os fins lícitos a que se propõe a plataforma, podendo inclusive manter tais dados em sua base por motivos pertinentes à legislação, mesmo no caso de o USUÁRIO ter seu cadastro excluído.
                    <br><br>IV.3 Após coletados e armazenados os dados, o MÃOCHEIA poderá disponibilizá-los aos USUÁRIOS para fins de aproximação entre as partes, tendo estes acesso às informações através da sua conta, os quais, seguindo as normas elencadas neste instrumento de contratação, poderão utilizá-las, editá-las ou excluí-las a qualquer tempo.
                    <br><br>IV.4  O MÃOCHEIA busca selecionar os mais seguros provedores de armazenamento de dados existentes, porém não se responsabiliza por eventos que fujam ao seu controle, os quais, por mais avançada que seja a tecnologia, podem comprometer a segurança e ocasionar falhas, tornando informações confidenciais vulneráveis ao ataque de hackers e outras pessoas que acessem ilegalmente tais informações.
                    <br><br><b>V - DAS OBRIGAÇÕES DOS USUÁRIOS</b>
                    <br><br>V.1 Caberá única e exclusivamente ao USUÁRIO PRESTADOR DE SERVIÇOS a emissão de nota fiscal de serviços, bem como a cobrança pelos serviços prestados ao USUÁRIO CLIENTE, não sendo a MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, responsável por eventual inadimplência, portanto devendo o prestador buscar os meios lícitos cabíveis na legislação vigente para recebimento das pendências.
                    <br><br>V.2 O USUÁRIO PRESTADOR DE SERVIÇOS deverá observar os bons padrões de qualidade quando da prestação dos serviços, utilizando desde equipamentos de proteção, trajes adequados, tratamento cordial e respeitoso junto aos USUÁRIOS CLIENTES, sob pena de ter seu cadastro excluído da plataforma, inclusive com recusa do MÃOCHEIA de recadastramento futuro.
                    <br><br>V.3 Caberá exclusivamente ao USUÁRIO CLIENTE exigir a emissão da nota fiscal referente ao serviço contratado, bem como tratar de todos os aspectos que envolvam a negociação, além do acompanhamento e supervisão da execução dos serviços, e também a exigência de certificação de garantia, visto que o mesmo está amparado pelo Código de Defesa do Consumidor.
                    <br><br>V.4 Quaisquer gastos que os USUÁRIOS venham a ter com ligações telefônicas, deslocamentos, despesas referentes à negociação ou execução dos serviços contratados, ou ainda com a viabilização de pagamentos/recebimentos, são de inteira responsabilidade dos mesmos, não tendo a empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, em hipótese alguma, obrigação de ressarci-los.
                    <br><br><b>VI - DAS VEDAÇÕES AO USO DA PLATAFORMA</b>
                    <br><br>VI.1 Não será permitido aos USUÁRIOS promoverem a publicidade de qualquer plataforma concorrente ao MÃOCHEIA, sob pena de ter o conteúdo excluído da plataforma ou mesmo suspensão, ou ainda o cancelamento do cadastro de USUÁRIO, sem necessidade de aviso prévio ao mesmo.
                    <br><br>VI.2 É expressamente proibida a divulgação de qualquer atividade, imagens ou comentários ilícitos por meio da plataforma MÃOCHEIA, incluindo frases que incitem a violência, o ódio, o racismo, a pornografia, as drogas, entre outros, que atentem à moral e os bons costumes, os quais serão excluídos unilateralmente pela MÃOCHEIA ANÚNCIOS DE INTERNET LTDA , procedendo-se a exclusão do cadastro do USUÁRIO responsável por tais atos, devendo o mesmo ainda responder civil e penalmente perante a legislação vigente.
                    <br><br>VI.3 Não serão toleradas palavras de baixo calão no uso da plataforma, portanto os USUÁRIOS que as utilizarem serão advertidos podendo inclusive ser banidos do MÃOCHEIA.
                    <br><br><b>VII - DA TARIFA</b>
                    <br><br>VII.1 Assim que o USUÁRIO PRESTADOR DE SERVIÇOS estiver cadastrado na plataforma, passará a receber notificações dos USUÁRIOS CLIENTES, solicitando serviços sobre os quais disponibilizarão informações conforme a categoria em que o prestador estiver cadastrado.
                    <br><br>VII.2 Ao visualizar as notificações, o USUÁRIO PRESTADOR DE SERVIÇOS utilizará moedas previamente adquiridas, as quais serão descontadas em uma quantidade variável conforme a classificação do serviço requisitado, para ter acesso aos dados do USUÁRIO CLIENTE. Assim, os mesmos poderão, através de um chat disponibilizado pela plataforma, negociar livremente, sem interferência do MÃOCHEIA, todos os aspectos referentes à contratação e prestação do serviço, conforme as condições de uso mencionadas neste Termo.
                    <br><br>VII.3 Uma vez descontadas as moedas, as mesmas não retornarão ao USUÁRIO PRESTADOR DE SERVIÇOS, mesmo que a negociação do serviço com o USUÁRIO CLENTE reste infrutífera e não ocorra a contratação dos seus serviços.
                    <br><br>VII.4 A MÃOCHEIA ANÚNCIOS DE INTERNET LTDA poderá, a seu critério e sem qualquer aviso prévio ao USUÁRIO PRESTADOR DE SERVIÇOS, alterar o preço e a forma de disponibilização de moedas, sendo que ao adquirir as moedas, o mesmo terá que usá-las no prazo de 12 (dose) meses, sob pena destas perderem a validade, não podendo o prestador resgatar o valor pago, mesmo que descadastre da plataforma.
                    <br><br><b>VIII - DAS DISPOSIÇÕES GERAIS</b>
                    <br><br>VIII.1 A MÃOCHEIA ANÚNCIOS DE INTERNET LTDA  poderá alterar as cláusulas constantes no presente instrumento a qualquer tempo e sem prévio aviso aos USUÁRIOS, seja por necessidade de manutenção da plataforma, seja para a adaptação às variações da economia e/ou como forma de enfrentar os novos desafios para uma constante evolução e consequente melhoramento dos serviços oferecidos pelo MÃOCHEIA aos USUÁRIOS.
                    <br><br>VIII.2 Em caso de alteração deste Termo, as mudanças entrarão em vigor no prazo de 15 (quinze) dias após serem divulgadas na plataforma, sendo que o USUÁRIO poderá manifestar-se neste período a respeito de tais mudanças, as quais poderão ser revistas pelos gestores do MÃOCHEIA, que tomarão as decisões que melhor couberem para o bom andamento da plataforma. A partir disso a permanência do USUÁRIO no MÃOCHEIA significará que o mesmo concorda com os novos termos, e assim passa a estar vinculado aos mesmos.
                    <br><br>VIII.3 Os direitos inerentes à plataforma MÃOCHEIA são exclusivos da empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, entre eles compreendidos marcas, patentes, imagens, logo, criações, domínios, e tudo mais por ela desenvolvidos e disponibilizados na plataforma, não sendo possível a qualquer USUÁRIO ou terceiro reivindicar direitos ou privilégios sobre os mesmos, nos termos da Lei nº 9.610/98.
                    <br><br>VIII.4 O presente instrumento não estabelece entre o USUÁRIO CLIENTE, o USUÁRIO PRESTADOR DE SERVIÇOS e a MÃOCHEIA ANÚNCIOS DE INTERNET LTDA, qualquer forma de sociedade ou vínculo empregatício, permanecendo cada qual de forma exclusiva com suas responsabilidades trabalhistas, fiscais, tributárias, cíveis, e criminais, nos termos da lei vigente.
                    <br><br>VIII.5 No caso de existir alguma controvérsia entre o USUÁRIO CLIENTE e o USUÁRIO PRESTADOR DE SERVIÇOS, e como consequência a empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA  for chamada para compor uma demanda judicial, o USUÁRIO que der causa à lide deverá arcar com todos os custos decorrentes da mesma, incluindo despesas com taxas, emolumentos, acordos, honorários advocatícios, entre outros.
                    <br><br>VIII.6 A empresa MÃOCHEIA ANÚNCIOS DE INTERNET LTDA  não será responsabilizada pelo mau funcionamento da plataforma, visto que, por mais que a mesma procure mantê-la em bom e pleno funcionamento, diversos fatores podem ocasionar falhas no sistema, tais quais, bugs, problemas com a internet, vírus, incompatibilidades com o dispositivo pelo qual o MÃOCHEIA está sendo acessado, entre outros, portanto não arcará com lucros cessantes, insucesso na viabilização de contatos, prestação de serviços etc.
                    <br><br>VIII.7 Este Termo constitui entendimento integral entre as partes, sendo eleito o foro da comarca de Criciúma/SC para dirimir quaisquer questões decorrentes do mesmo, renunciando a qualquer outro, por mais privilegiado que seja.
                </div>
            </div>
        </div>
</section>